package com.cnpm.model;
// Generated Aug 16, 2020 11:09:57 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Booking generated by hbm2java
 */
@Entity
@Table(name = "booking", catalog = "onlinehotel")
public class Booking implements java.io.Serializable {

	private int id;
	private String customerName;
	private String customerEmail;
	private String cusomerAddress;
	private String customerPhone;
	private Date createDate;
	private String status;
	private String requirement;

	public Booking() {
	}

	public Booking(int id, String customerName, String customerEmail, String cusomerAddress, String customerPhone,
			Date createDate, String status) {
		this.id = id;
		this.customerName = customerName;
		this.customerEmail = customerEmail;
		this.cusomerAddress = cusomerAddress;
		this.customerPhone = customerPhone;
		this.createDate = createDate;
		this.status = status;
	}

	public Booking(int id, String customerName, String customerEmail, String cusomerAddress, String customerPhone,
			Date createDate, String status, String requirement) {
		this.id = id;
		this.customerName = customerName;
		this.customerEmail = customerEmail;
		this.cusomerAddress = cusomerAddress;
		this.customerPhone = customerPhone;
		this.createDate = createDate;
		this.status = status;
		this.requirement = requirement;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "customer_name", nullable = false, length = 45)
	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	@Column(name = "customer_email", nullable = false, length = 45)
	public String getCustomerEmail() {
		return this.customerEmail;
	}

	public void setCustomerEmail(String customerEmail) {
		this.customerEmail = customerEmail;
	}

	@Column(name = "cusomer_address", nullable = false, length = 45)
	public String getCusomerAddress() {
		return this.cusomerAddress;
	}

	public void setCusomerAddress(String cusomerAddress) {
		this.cusomerAddress = cusomerAddress;
	}

	@Column(name = "customer_phone", nullable = false, length = 45)
	public String getCustomerPhone() {
		return this.customerPhone;
	}

	public void setCustomerPhone(String customerPhone) {
		this.customerPhone = customerPhone;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "create_date", nullable = false, length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "status", nullable = false, length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "requirement", length = 45)
	public String getRequirement() {
		return this.requirement;
	}

	public void setRequirement(String requirement) {
		this.requirement = requirement;
	}

}
