package com.cnpm.model;
// Generated Aug 16, 2020 11:09:57 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Roomtype generated by hbm2java
 */
@Entity
@Table(name = "roomtype", catalog = "onlinehotel")
public class Roomtype implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<Room> rooms = new HashSet<Room>(0);

	public Roomtype() {
	}

	public Roomtype(String name) {
		this.name = name;
	}

	public Roomtype(String name, Set<Room> rooms) {
		this.name = name;
		this.rooms = rooms;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "roomtype")
	public Set<Room> getRooms() {
		return this.rooms;
	}

	public void setRooms(Set<Room> rooms) {
		this.rooms = rooms;
	}

}
