package com.cnpm.model;
// Generated Aug 11, 2020 2:59:28 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Booking generated by hbm2java
 */
@Entity
@Table(name = "booking", catalog = "onlinehotel")
public class Booking implements java.io.Serializable {

	private Integer bookingId;
	private String customerName;
	private String customerEmail;
	private String customerPhone;
	private String bookingDate;
	private String checkIn;
	private String checkOut;
	private Set<BookingDetail> bookingDetails = new HashSet<BookingDetail>(0);

	public Booking() {
	}

	public Booking(String customerName, String customerEmail, String customerPhone, String bookingDate, String checkIn,
			String checkOut) {
		this.customerName = customerName;
		this.customerEmail = customerEmail;
		this.customerPhone = customerPhone;
		this.bookingDate = bookingDate;
		this.checkIn = checkIn;
		this.checkOut = checkOut;
	}

	public Booking(String customerName, String customerEmail, String customerPhone, String bookingDate, String checkIn,
			String checkOut, Set<BookingDetail> bookingDetails) {
		this.customerName = customerName;
		this.customerEmail = customerEmail;
		this.customerPhone = customerPhone;
		this.bookingDate = bookingDate;
		this.checkIn = checkIn;
		this.checkOut = checkOut;
		this.bookingDetails = bookingDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "booking_id", unique = true, nullable = false)
	public Integer getBookingId() {
		return this.bookingId;
	}

	public void setBookingId(Integer bookingId) {
		this.bookingId = bookingId;
	}

	@Column(name = "customer_name", nullable = false, length = 45)
	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	@Column(name = "customer_email", nullable = false, length = 45)
	public String getCustomerEmail() {
		return this.customerEmail;
	}

	public void setCustomerEmail(String customerEmail) {
		this.customerEmail = customerEmail;
	}

	@Column(name = "customer_phone", nullable = false, length = 45)
	public String getCustomerPhone() {
		return this.customerPhone;
	}

	public void setCustomerPhone(String customerPhone) {
		this.customerPhone = customerPhone;
	}

	@Column(name = "booking_date", nullable = false, length = 45)
	public String getBookingDate() {
		return this.bookingDate;
	}

	public void setBookingDate(String bookingDate) {
		this.bookingDate = bookingDate;
	}

	@Column(name = "check_in", nullable = false, length = 45)
	public String getCheckIn() {
		return this.checkIn;
	}

	public void setCheckIn(String checkIn) {
		this.checkIn = checkIn;
	}

	@Column(name = "check_out", nullable = false, length = 45)
	public String getCheckOut() {
		return this.checkOut;
	}

	public void setCheckOut(String checkOut) {
		this.checkOut = checkOut;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "booking")
	public Set<BookingDetail> getBookingDetails() {
		return this.bookingDetails;
	}

	public void setBookingDetails(Set<BookingDetail> bookingDetails) {
		this.bookingDetails = bookingDetails;
	}

}
