package com.cnpm.model;
// Generated Aug 10, 2020 9:49:16 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Roomimage generated by hbm2java
 */
@Entity
@Table(name = "roomimage", catalog = "onlinehotel")
public class Roomimage implements java.io.Serializable {

	private Integer id;
	private Room room;
	private String mainImage;

	public Roomimage() {
	}

	public Roomimage(Room room, String mainImage) {
		this.room = room;
		this.mainImage = mainImage;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "room_id", nullable = false)
	public Room getRoom() {
		return this.room;
	}

	public void setRoom(Room room) {
		this.room = room;
	}

	@Column(name = "main_image", nullable = false, length = 45)
	public String getMainImage() {
		return this.mainImage;
	}

	public void setMainImage(String mainImage) {
		this.mainImage = mainImage;
	}

}
