package com.cnpm.model;
// Generated Aug 10, 2020 12:03:13 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Room generated by hbm2java
 */
@Entity
@Table(name = "room", catalog = "onlinehotel")
public class Room implements java.io.Serializable {

	private Integer roomId;
	private Roomtype roomtype;
	private String roomName;
	private String roomPrice;
	private String roomService;
	private String roomSize;

	public Room() {
	}

	public Room(Roomtype roomtype, String roomName, String roomPrice, String roomService, String roomSize) {
		this.roomtype = roomtype;
		this.roomName = roomName;
		this.roomPrice = roomPrice;
		this.roomService = roomService;
		this.roomSize = roomSize;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "room_id", unique = true, nullable = false)
	public Integer getRoomId() {
		return this.roomId;
	}

	public void setRoomId(Integer roomId) {
		this.roomId = roomId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "roomtype_id", nullable = false)
	public Roomtype getRoomtype() {
		return this.roomtype;
	}

	public void setRoomtype(Roomtype roomtype) {
		this.roomtype = roomtype;
	}

	@Column(name = "room_name", nullable = false, length = 45)
	public String getRoomName() {
		return this.roomName;
	}

	public void setRoomName(String roomName) {
		this.roomName = roomName;
	}

	@Column(name = "room_price", nullable = false, length = 45)
	public String getRoomPrice() {
		return this.roomPrice;
	}

	public void setRoomPrice(String roomPrice) {
		this.roomPrice = roomPrice;
	}

	@Column(name = "room_service", nullable = false, length = 45)
	public String getRoomService() {
		return this.roomService;
	}

	public void setRoomService(String roomService) {
		this.roomService = roomService;
	}

	@Column(name = "room_size", nullable = false, length = 45)
	public String getRoomSize() {
		return this.roomSize;
	}

	public void setRoomSize(String roomSize) {
		this.roomSize = roomSize;
	}

}
