package com.cnpm.model;
// Generated Aug 8, 2020 8:22:53 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Room generated by hbm2java
 */
@Entity
@Table(name = "room", catalog = "onlinehotel")
public class Room implements java.io.Serializable {

	private Integer roomId;
	private Roomtype roomtype;
	private String roomName;
	private int roomPrice;
	private String roomCapacity;
	private int roomSize;

	public Room() {
	}

	public Room(Roomtype roomtype, String roomName, int roomPrice, String roomCapacity, int roomSize) {
		this.roomtype = roomtype;
		this.roomName = roomName;
		this.roomPrice = roomPrice;
		this.roomCapacity = roomCapacity;
		this.roomSize = roomSize;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "room_id", unique = true, nullable = false)
	public Integer getRoomId() {
		return this.roomId;
	}

	public void setRoomId(Integer roomId) {
		this.roomId = roomId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "roomtype_id", nullable = false)
	public Roomtype getRoomtype() {
		return this.roomtype;
	}

	public void setRoomtype(Roomtype roomtype) {
		this.roomtype = roomtype;
	}

	@Column(name = "room_name", nullable = false, length = 45)
	public String getRoomName() {
		return this.roomName;
	}

	public void setRoomName(String roomName) {
		this.roomName = roomName;
	}

	@Column(name = "room_price", nullable = false)
	public int getRoomPrice() {
		return this.roomPrice;
	}

	public void setRoomPrice(int roomPrice) {
		this.roomPrice = roomPrice;
	}

	@Column(name = "room_capacity", nullable = false, length = 45)
	public String getRoomCapacity() {
		return this.roomCapacity;
	}

	public void setRoomCapacity(String roomCapacity) {
		this.roomCapacity = roomCapacity;
	}

	@Column(name = "room_size", nullable = false)
	public int getRoomSize() {
		return this.roomSize;
	}

	public void setRoomSize(int roomSize) {
		this.roomSize = roomSize;
	}

}
